DROP DATABASE IF EXISTS project;
CREATE DATABASE project;

DROP USER IF EXISTS admin;
CREATE USER admin WITH PASSWORD 'admin';

GRANT ALL PRIVILEGES ON DATABASE project TO admin;


ALTER DATABASE project OWNER TO admin;
ALTER USER admin WITH SUPERUSER;

